### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by r4f4** [modularity-modules/dhcp#2]
package: perl-SGMLSpm-1.03ii-39.module_0b20512d.noarch from repoclosure-Server.x86_64
  unresolved deps: 
     openjade

As for openjade deps, you'll probably need opensp.

**Comment by phracek** [comment]
Although I have filter out perl-SGMLSpm package. dhcp was not build n Fedora dist-git.
@nphilipp Please merge it and build so repoclosure is fixed. https://github.com/modularity-modules/dhcp/pull/1

**Comment by r4f4** [comment]
I see dhcp includes some packages already included by base-runtime:
`libnetfilter_conntrack`
`libnfnetlink`
`iproute`
`libmnl`

**Comment by nphilipp** [comment]
@KarstenHopp fixed these meanwhile.
